### ISSUE TITLE
No Docker Images Started after install

### ISSUE THREAD

**Issue by mon5termatt** [LordZeuss/arr-installer#3]
Would you like to install Sonarr? (y/n/f/e)
 
ymkdir: cannot create directory '/home/media/raspi-docker/sonarr': File exists
mkdir: cannot create directory '/home/media/raspi-docker/sonarr/config': File exists
 
Successfully Added
Would you like to install Radarr? (y/n/f/e)
ymkdir: cannot create directory '/home/media/raspi-docker/radarr': File exists
mkdir: cannot create directory '/home/media/raspi-docker/radarr/config': File exists
 
Successfully Added
Would you like install Prowlarr? (y/n/f/e)
n 
Skipping...
Would you like to install Jackett (Required for Sonarr/Radarr)? (y/n/f/e)
y 
Successfully Added
Would you like install Jellyfin Media Server? (y/n/f/e)
n 
Skipping...
Would you like to install Plex Media Server? (y/n/f/e)
n 
Skipping...
Would you like to install Emby? (y/n/f/e)
n 
Skipping...
Would you like to install AdGuard (DNS Adblocker)? (y/n/f/e)
n 
Skipping...
Would you like to install Readarr? (y/n/f/e)
n 
Skipping...
Would you like to install Bazarr (Subtitles)? (y/n/f/e)
n 
Skipping...
Would you like to install Overseerr? (y/n/f/e)
n 
Skipping...
Would you like to install Lidarr (Music)? (y/n/f/e)
y 
Successfully Added
Would you like to install Podgrab? (y/n/f/e)
n 
Skipping...
Would you like to install Heimdall? (y/n/f/e)
n 
Skipping...
 
 
Installer Complete. Run torrent-clients-installer.sh if you would like to install a torrent client as well.
 
To access Portainer, go to the IP of this device in a web-browser, port 9000. Ex: 192.168.1.18:9000
Goodbye!

media@arr:~/arr-installer$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

media@arr:~/arr-installer$

**Comment by mon5termatt** [comment]
Recommend to have an option in the script to restart the docker containers after install

**Comment by mon5termatt** [comment]
Running Docker-Compose up -d results in the following error

Debian 11 via Proxmox


Starting sonarr      ... 
Creating bazarr      ... 
Starting lidarr      ... 
Starting radarr      ... 
Creating overseerr   ... 
Starting jackett     ... 
Creating prowlarr    ... 
Creating readarr     ... 

ERROR: for sonarr  a bytes-like object is required, not 'str'

ERROR: for lidarr  a bytes-like object is required, not 'str'

ERROR: for radarr  a bytes-like object is required, not 'str'

ERROR: for jackett  a bytes-like object is required, not 'str'

ERROR: for readarr  a bytes-like object is required, not 'str'

ERROR: for overseerr  a bytes-like object is required, not 'str'

ERROR: for bazarr  a bytes-like object is required, not 'str'

ERROR: for portainer  a bytes-like object is required, not 'str'

ERROR: for prowlarr  a bytes-like object is required, not 'str'

ERROR: for sonarr  a bytes-like object is required, not 'str'

ERROR: for lidarr  a bytes-like object is required, not 'str'

ERROR: for radarr  a bytes-like object is required, not 'str'

ERROR: for jackett  a bytes-like object is required, not 'str'

ERROR: for readarr  a bytes-like object is required, not 'str'

ERROR: for overseerr  a bytes-like object is required, not 'str'

ERROR: for bazarr  a bytes-like object is required, not 'str'

ERROR: for portainer  a bytes-like object is required, not 'str'

ERROR: for prowlarr  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.21/containers/6f587ca27708719a150acabbfa13a373653b48dd8bfd4d0f84c91098323f5cb3/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b"OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown"")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 545, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 460, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 465, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 457, in create_and_start
    self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'

**Comment by LordZeuss** [comment]
Thank you for adding the errors. I will look into adding a container restart as well. I believe if you were to delete the files that say they exist, that would hopefully eliminate the issue, if not determine if it's this script, or a docker issue.

It looks like that may be a docker issue, so I would recommend deleting the docker-compose.yml file, and trying again. The script will add the docker-compose information to that file, so that the user can run/modify the compose file. If it is not downloading or running the containers properly, I want to believe that is a docker issue. I would see if it's possible to reinstall docker, or if it's a fresh VM, attempt to delete it and start from fresh and see if you get the same issue. Based on the logs, its calling to the docker compose files, and I would make sure that docker and docker compose are installed first, and if its functional.

docker -v or docker-compose -v should tell you if docker is there.

Let me know if there is anything that I can do to help!
